
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `note` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model note
 * 
 */
export type noteModel = runtime.Types.Result.DefaultSelection<Prisma.$notePayload>

export type AggregateNote = {
  _count: NoteCountAggregateOutputType | null
  _avg: NoteAvgAggregateOutputType | null
  _sum: NoteSumAggregateOutputType | null
  _min: NoteMinAggregateOutputType | null
  _max: NoteMaxAggregateOutputType | null
}

export type NoteAvgAggregateOutputType = {
  id: number | null
}

export type NoteSumAggregateOutputType = {
  id: number | null
}

export type NoteMinAggregateOutputType = {
  id: number | null
  title: string | null
  content: string | null
  archived: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NoteMaxAggregateOutputType = {
  id: number | null
  title: string | null
  content: string | null
  archived: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NoteCountAggregateOutputType = {
  id: number
  title: number
  content: number
  archived: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type NoteAvgAggregateInputType = {
  id?: true
}

export type NoteSumAggregateInputType = {
  id?: true
}

export type NoteMinAggregateInputType = {
  id?: true
  title?: true
  content?: true
  archived?: true
  createdAt?: true
  updatedAt?: true
}

export type NoteMaxAggregateInputType = {
  id?: true
  title?: true
  content?: true
  archived?: true
  createdAt?: true
  updatedAt?: true
}

export type NoteCountAggregateInputType = {
  id?: true
  title?: true
  content?: true
  archived?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type NoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which note to aggregate.
   */
  where?: Prisma.noteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of notes to fetch.
   */
  orderBy?: Prisma.noteOrderByWithRelationInput | Prisma.noteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.noteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` notes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` notes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned notes
  **/
  _count?: true | NoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NoteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NoteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NoteMaxAggregateInputType
}

export type GetNoteAggregateType<T extends NoteAggregateArgs> = {
      [P in keyof T & keyof AggregateNote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNote[P]>
    : Prisma.GetScalarType<T[P], AggregateNote[P]>
}




export type noteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.noteWhereInput
  orderBy?: Prisma.noteOrderByWithAggregationInput | Prisma.noteOrderByWithAggregationInput[]
  by: Prisma.NoteScalarFieldEnum[] | Prisma.NoteScalarFieldEnum
  having?: Prisma.noteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NoteCountAggregateInputType | true
  _avg?: NoteAvgAggregateInputType
  _sum?: NoteSumAggregateInputType
  _min?: NoteMinAggregateInputType
  _max?: NoteMaxAggregateInputType
}

export type NoteGroupByOutputType = {
  id: number
  title: string
  content: string
  archived: boolean
  createdAt: Date
  updatedAt: Date
  _count: NoteCountAggregateOutputType | null
  _avg: NoteAvgAggregateOutputType | null
  _sum: NoteSumAggregateOutputType | null
  _min: NoteMinAggregateOutputType | null
  _max: NoteMaxAggregateOutputType | null
}

type GetNoteGroupByPayload<T extends noteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NoteGroupByOutputType[P]>
      }
    >
  >



export type noteWhereInput = {
  AND?: Prisma.noteWhereInput | Prisma.noteWhereInput[]
  OR?: Prisma.noteWhereInput[]
  NOT?: Prisma.noteWhereInput | Prisma.noteWhereInput[]
  id?: Prisma.IntFilter<"note"> | number
  title?: Prisma.StringFilter<"note"> | string
  content?: Prisma.StringFilter<"note"> | string
  archived?: Prisma.BoolFilter<"note"> | boolean
  createdAt?: Prisma.DateTimeFilter<"note"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"note"> | Date | string
}

export type noteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type noteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.noteWhereInput | Prisma.noteWhereInput[]
  OR?: Prisma.noteWhereInput[]
  NOT?: Prisma.noteWhereInput | Prisma.noteWhereInput[]
  title?: Prisma.StringFilter<"note"> | string
  content?: Prisma.StringFilter<"note"> | string
  archived?: Prisma.BoolFilter<"note"> | boolean
  createdAt?: Prisma.DateTimeFilter<"note"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"note"> | Date | string
}, "id">

export type noteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.noteCountOrderByAggregateInput
  _avg?: Prisma.noteAvgOrderByAggregateInput
  _max?: Prisma.noteMaxOrderByAggregateInput
  _min?: Prisma.noteMinOrderByAggregateInput
  _sum?: Prisma.noteSumOrderByAggregateInput
}

export type noteScalarWhereWithAggregatesInput = {
  AND?: Prisma.noteScalarWhereWithAggregatesInput | Prisma.noteScalarWhereWithAggregatesInput[]
  OR?: Prisma.noteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.noteScalarWhereWithAggregatesInput | Prisma.noteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"note"> | number
  title?: Prisma.StringWithAggregatesFilter<"note"> | string
  content?: Prisma.StringWithAggregatesFilter<"note"> | string
  archived?: Prisma.BoolWithAggregatesFilter<"note"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"note"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"note"> | Date | string
}

export type noteCreateInput = {
  title: string
  content: string
  archived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type noteUncheckedCreateInput = {
  id?: number
  title: string
  content: string
  archived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type noteUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type noteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type noteCreateManyInput = {
  id?: number
  title: string
  content: string
  archived?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type noteUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type noteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  archived?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type noteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type noteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type noteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type noteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  archived?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type noteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type noteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  archived?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["note"]>

export type noteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  archived?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["note"]>

export type noteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  archived?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["note"]>

export type noteSelectScalar = {
  id?: boolean
  title?: boolean
  content?: boolean
  archived?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type noteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "content" | "archived" | "createdAt" | "updatedAt", ExtArgs["result"]["note"]>

export type $notePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "note"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string
    content: string
    archived: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["note"]>
  composites: {}
}

export type noteGetPayload<S extends boolean | null | undefined | noteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$notePayload, S>

export type noteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<noteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NoteCountAggregateInputType | true
  }

export interface noteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['note'], meta: { name: 'note' } }
  /**
   * Find zero or one Note that matches the filter.
   * @param {noteFindUniqueArgs} args - Arguments to find a Note
   * @example
   * // Get one Note
   * const note = await prisma.note.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends noteFindUniqueArgs>(args: Prisma.SelectSubset<T, noteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__noteClient<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Note that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {noteFindUniqueOrThrowArgs} args - Arguments to find a Note
   * @example
   * // Get one Note
   * const note = await prisma.note.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends noteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, noteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__noteClient<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Note that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {noteFindFirstArgs} args - Arguments to find a Note
   * @example
   * // Get one Note
   * const note = await prisma.note.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends noteFindFirstArgs>(args?: Prisma.SelectSubset<T, noteFindFirstArgs<ExtArgs>>): Prisma.Prisma__noteClient<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Note that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {noteFindFirstOrThrowArgs} args - Arguments to find a Note
   * @example
   * // Get one Note
   * const note = await prisma.note.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends noteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, noteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__noteClient<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Notes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {noteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Notes
   * const notes = await prisma.note.findMany()
   * 
   * // Get first 10 Notes
   * const notes = await prisma.note.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const noteWithIdOnly = await prisma.note.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends noteFindManyArgs>(args?: Prisma.SelectSubset<T, noteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Note.
   * @param {noteCreateArgs} args - Arguments to create a Note.
   * @example
   * // Create one Note
   * const Note = await prisma.note.create({
   *   data: {
   *     // ... data to create a Note
   *   }
   * })
   * 
   */
  create<T extends noteCreateArgs>(args: Prisma.SelectSubset<T, noteCreateArgs<ExtArgs>>): Prisma.Prisma__noteClient<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Notes.
   * @param {noteCreateManyArgs} args - Arguments to create many Notes.
   * @example
   * // Create many Notes
   * const note = await prisma.note.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends noteCreateManyArgs>(args?: Prisma.SelectSubset<T, noteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Notes and returns the data saved in the database.
   * @param {noteCreateManyAndReturnArgs} args - Arguments to create many Notes.
   * @example
   * // Create many Notes
   * const note = await prisma.note.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Notes and only return the `id`
   * const noteWithIdOnly = await prisma.note.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends noteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, noteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Note.
   * @param {noteDeleteArgs} args - Arguments to delete one Note.
   * @example
   * // Delete one Note
   * const Note = await prisma.note.delete({
   *   where: {
   *     // ... filter to delete one Note
   *   }
   * })
   * 
   */
  delete<T extends noteDeleteArgs>(args: Prisma.SelectSubset<T, noteDeleteArgs<ExtArgs>>): Prisma.Prisma__noteClient<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Note.
   * @param {noteUpdateArgs} args - Arguments to update one Note.
   * @example
   * // Update one Note
   * const note = await prisma.note.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends noteUpdateArgs>(args: Prisma.SelectSubset<T, noteUpdateArgs<ExtArgs>>): Prisma.Prisma__noteClient<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Notes.
   * @param {noteDeleteManyArgs} args - Arguments to filter Notes to delete.
   * @example
   * // Delete a few Notes
   * const { count } = await prisma.note.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends noteDeleteManyArgs>(args?: Prisma.SelectSubset<T, noteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Notes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {noteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Notes
   * const note = await prisma.note.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends noteUpdateManyArgs>(args: Prisma.SelectSubset<T, noteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Notes and returns the data updated in the database.
   * @param {noteUpdateManyAndReturnArgs} args - Arguments to update many Notes.
   * @example
   * // Update many Notes
   * const note = await prisma.note.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Notes and only return the `id`
   * const noteWithIdOnly = await prisma.note.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends noteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, noteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Note.
   * @param {noteUpsertArgs} args - Arguments to update or create a Note.
   * @example
   * // Update or create a Note
   * const note = await prisma.note.upsert({
   *   create: {
   *     // ... data to create a Note
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Note we want to update
   *   }
   * })
   */
  upsert<T extends noteUpsertArgs>(args: Prisma.SelectSubset<T, noteUpsertArgs<ExtArgs>>): Prisma.Prisma__noteClient<runtime.Types.Result.GetResult<Prisma.$notePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Notes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {noteCountArgs} args - Arguments to filter Notes to count.
   * @example
   * // Count the number of Notes
   * const count = await prisma.note.count({
   *   where: {
   *     // ... the filter for the Notes we want to count
   *   }
   * })
  **/
  count<T extends noteCountArgs>(
    args?: Prisma.Subset<T, noteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Note.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NoteAggregateArgs>(args: Prisma.Subset<T, NoteAggregateArgs>): Prisma.PrismaPromise<GetNoteAggregateType<T>>

  /**
   * Group by Note.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {noteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends noteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: noteGroupByArgs['orderBy'] }
      : { orderBy?: noteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, noteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the note model
 */
readonly fields: noteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for note.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__noteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the note model
 */
export interface noteFieldRefs {
  readonly id: Prisma.FieldRef<"note", 'Int'>
  readonly title: Prisma.FieldRef<"note", 'String'>
  readonly content: Prisma.FieldRef<"note", 'String'>
  readonly archived: Prisma.FieldRef<"note", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"note", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"note", 'DateTime'>
}
    

// Custom InputTypes
/**
 * note findUnique
 */
export type noteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * Filter, which note to fetch.
   */
  where: Prisma.noteWhereUniqueInput
}

/**
 * note findUniqueOrThrow
 */
export type noteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * Filter, which note to fetch.
   */
  where: Prisma.noteWhereUniqueInput
}

/**
 * note findFirst
 */
export type noteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * Filter, which note to fetch.
   */
  where?: Prisma.noteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of notes to fetch.
   */
  orderBy?: Prisma.noteOrderByWithRelationInput | Prisma.noteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for notes.
   */
  cursor?: Prisma.noteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` notes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` notes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of notes.
   */
  distinct?: Prisma.NoteScalarFieldEnum | Prisma.NoteScalarFieldEnum[]
}

/**
 * note findFirstOrThrow
 */
export type noteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * Filter, which note to fetch.
   */
  where?: Prisma.noteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of notes to fetch.
   */
  orderBy?: Prisma.noteOrderByWithRelationInput | Prisma.noteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for notes.
   */
  cursor?: Prisma.noteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` notes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` notes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of notes.
   */
  distinct?: Prisma.NoteScalarFieldEnum | Prisma.NoteScalarFieldEnum[]
}

/**
 * note findMany
 */
export type noteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * Filter, which notes to fetch.
   */
  where?: Prisma.noteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of notes to fetch.
   */
  orderBy?: Prisma.noteOrderByWithRelationInput | Prisma.noteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing notes.
   */
  cursor?: Prisma.noteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` notes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` notes.
   */
  skip?: number
  distinct?: Prisma.NoteScalarFieldEnum | Prisma.NoteScalarFieldEnum[]
}

/**
 * note create
 */
export type noteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * The data needed to create a note.
   */
  data: Prisma.XOR<Prisma.noteCreateInput, Prisma.noteUncheckedCreateInput>
}

/**
 * note createMany
 */
export type noteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many notes.
   */
  data: Prisma.noteCreateManyInput | Prisma.noteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * note createManyAndReturn
 */
export type noteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * The data used to create many notes.
   */
  data: Prisma.noteCreateManyInput | Prisma.noteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * note update
 */
export type noteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * The data needed to update a note.
   */
  data: Prisma.XOR<Prisma.noteUpdateInput, Prisma.noteUncheckedUpdateInput>
  /**
   * Choose, which note to update.
   */
  where: Prisma.noteWhereUniqueInput
}

/**
 * note updateMany
 */
export type noteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update notes.
   */
  data: Prisma.XOR<Prisma.noteUpdateManyMutationInput, Prisma.noteUncheckedUpdateManyInput>
  /**
   * Filter which notes to update
   */
  where?: Prisma.noteWhereInput
  /**
   * Limit how many notes to update.
   */
  limit?: number
}

/**
 * note updateManyAndReturn
 */
export type noteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * The data used to update notes.
   */
  data: Prisma.XOR<Prisma.noteUpdateManyMutationInput, Prisma.noteUncheckedUpdateManyInput>
  /**
   * Filter which notes to update
   */
  where?: Prisma.noteWhereInput
  /**
   * Limit how many notes to update.
   */
  limit?: number
}

/**
 * note upsert
 */
export type noteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * The filter to search for the note to update in case it exists.
   */
  where: Prisma.noteWhereUniqueInput
  /**
   * In case the note found by the `where` argument doesn't exist, create a new note with this data.
   */
  create: Prisma.XOR<Prisma.noteCreateInput, Prisma.noteUncheckedCreateInput>
  /**
   * In case the note was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.noteUpdateInput, Prisma.noteUncheckedUpdateInput>
}

/**
 * note delete
 */
export type noteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
  /**
   * Filter which note to delete.
   */
  where: Prisma.noteWhereUniqueInput
}

/**
 * note deleteMany
 */
export type noteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which notes to delete
   */
  where?: Prisma.noteWhereInput
  /**
   * Limit how many notes to delete.
   */
  limit?: number
}

/**
 * note without action
 */
export type noteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the note
   */
  select?: Prisma.noteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the note
   */
  omit?: Prisma.noteOmit<ExtArgs> | null
}
